# Generated by Django 4.2.2 on 2023-07-10 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='classes_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
