# Generated by Django 4.2.2 on 2023-07-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_class_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='address',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
