# Generated by Django 4.2.2 on 2023-07-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('class', '0004_alter_likes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to='account.profile'),
        ),
    ]
