# Generated by Django 4.2.2 on 2023-07-04 12:54

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_class_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
